plugins {
    id 'application'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
    implementation project(':core')
    implementation 'com.google.zxing:core:3.5.3'

    compileOnly 'org.projectlombok:lombok:1.18.34'
    annotationProcessor 'org.projectlombok:lombok:1.18.34'

    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

application {
    mainClass = 'com.mu.qrcodestream.emitter.Main'
}

tasks.named('jar') {
    manifest {
        attributes 'Main-Class': application.mainClass.get()
    }
}

test {
    useJUnitPlatform()
}
